# Generated by Django 4.0.3 on 2022-04-20 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CENGGSentimentOutput',
            fields=[
                ('comments', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('sentiments', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'cenggsentimentoutput',
            },
        ),
    ]
