# Generated by Django 4.0.3 on 2022-04-20 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_cenggsentimentoutput'),
    ]

    operations = [
        migrations.CreateModel(
            name='CENGGEmotionOutput',
            fields=[
                ('label', models.CharField(max_length=100)),
                ('score', models.CharField(max_length=30)),
                ('comments', models.CharField(max_length=100, primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'cenggemotionoutput',
            },
        ),
        migrations.AddField(
            model_name='emotionoutput',
            name='comments',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
